on:
  push:
    branches:
      - prod

jobs:
  deploy-prod:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Fabric Production
        run: echo "Deploying to Fabric Prod"
